daemonize
show-failed-attempts
clock
screenshot
effect-blur=9x5
effect-vignette=0.5:0.5
color=1f1d2e80
font="Inter"
indicator
indicator-radius=200
indicator-thickness=20

line-color=#32302f
ring-color=#32302f
inside-color=#282828
key-hl-color=#689d6a

separator-color=00000000
text-color=#ebdbb2

text-caps-lock-color=""
line-ver-color=#689d6a
ring-ver-color=#689d6a
inside-ver-color=#282828
text-ver-color=#ebdbb2

ring-wrong-color=#cc241d
text-wrong-color=#cc241d
inside-wrong-color=#282828
inside-clear-color=#282828

text-clear-color=ebdbb2
ring-clear-color=fb4934
line-clear-color=#282828
line-wrong-color=#282828
bs-hl-color=cc241d
grace=2
grace-no-mouse
grace-no-touch
datestr=%a, %B %e
timestr=%I:%M %p
fade-in=0.2
ignore-empty-password
