#!/bin/sh

export LANG="POSIX"

user="${USER-$(id -u -n)}"
host="$(uname -n)"
shell="${SHELL##*/}"
pkg="$(pacman -Qq | wc -l)"
wm="$(ps -e | grep -m1 -Fo -e asc \
								-e bspwn\
								-e i3\
								-e dwc\
								-e dwm\
								-e xmonad\
								-e sway\
								-e awesome)"

c0=$'\e[0m'
c1=$'\e[1;31m'
c2=$'\e[1;32m'
c3=$'\e[1;33m'
c4=$'\e[1;34m'
c5=$'\e[1;35m'
c6=$'\e[1;36m'
c7=$'\e[1;37m'
c8=$'\e[1;38m'
c9=$'\e[1;39m'

echo -n "$c5${user}$c3@$c4${host} $c6${shell} $c7${wm} $c2${pkg}"
