#! /usr/bin/python
import sys
import socket
from tabulate import tabulate

class colors:
	cyan   = '\033[96m'
	purple = '\033[95m'
	blue   = '\033[94m'
	green  = '\033[92m'
	yellow = '\033[93m'
	red	   = '\033[91m'
	l_gray = '\033[90m'
	reset  = '\033[0m'

def cl(c, line):
	return c + line.strip() + colors.reset

table = []
headers = [cl(colors.cyan, "ip"), cl(colors.yellow, "host")]

for line in sys.stdin:
	h_name = socket.getfqdn(line)
	table.append([cl(colors.blue, line), h_name])

print(tabulate(table, headers=headers, tablefmt="grid", stralign='center'))
