#!/bin/bash

scan_net() {
	if [ "$1" == "" ] 
	then 
		echo "No ip addr"
		echo "Syntax: ./ipsweep.sh 192.168.2"
	else
		for ip in `seq 1 254`; do
			ping -c 2 -w 1 $1.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" &
		done; wait
	fi
}

if [ $# -eq 0 ]; then
	ip_addr=$(ip -brief addr | grep -E -o "192.168.[0-9]{1,3}")
	
	~/my_utils/ipsweep.sh "$ip_addr" | ~/my_utils/hawk

else
	~/my_utils/ipsweep.sh $1 | ~/my_utils/hawk
fi
